version: '3.4'

services:
  minecraftbackbone:
    build:
      context: .
      args:
        RAM-AMMOUNT: ${RAM_AMMOUNT}
    volumes:
      - .server-data:/server
    ports:
      - 25565:25565
      - 25575:25575
    container_name: ${CONTAINER_NAME}
    
volumes:
  server-data:


